RPM: Change dependency for rhel 9
Rhel 9 ansible package is not longer ansible, so things started to fail:

```
rpm-md repo 'copr:copr.fedorainfracloud.org:project-flotta:flotta-testing' (cached); generated: 2022-06-14T03:23:00Z solvables: 17
Resolving dependencies... done
error: Could not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - nothing provides ansible needed by flotta-agent-0.1.0-1.el9.x86_64
```

And the same for compose-cli:

```
$ -> sudo composer-cli blueprints show Edge | head
name = "Edge"
description = ""
version = "0.0.2"
packages = []
groups = []
distro = ""

[[modules]]
name = "ansible"
version = "*"
$ -> sudo composer-cli blueprints depsolve Edge
ERROR: BlueprintsError: Edge: DNF error occured: MarkingErrors: Error occurred when marking packages for installation: Problems in request:
missing packages: ansible
blueprint: Edge v0.0.2
```

Signed-off-by: Eloy Coto <eloy.coto@acalustra.com>